### ISSUE TITLE
Script no longer works on El Goonish Shive after an url schema change

### ISSUE THREAD

**Issue by m2pt5** [anka-213/webcomic_reader#118]
http://www.egscomics.com/

Also, the page layout has changed a bit, so the part that catches the commentary will need to be fixed too.

**Comment by SoraHjort** [comment]
Can confirm. It's been like this for some time now.

**Comment by anka-213** [comment]
It should work now. Please tell me if there are still issues.

**Comment by m2pt5** [comment]
Looks mostly good, out of personal preference I added 'style="text-align:left"' to the div around the duplicated news, so it's aligned the same as the original, rather than centered. (I don't know how to submit a pull request for that or I would.)

**Comment by anka-213** [comment]
@m2pt5  You can click on the source file in github and press the "Edit" button on the top right, then make the change and press "Propose file change". See this guide: https://help.github.com/articles/editing-files-in-another-user-s-repository/
