### ISSUE TITLE
Mangapark updated domain

### ISSUE THREAD

**Issue by j2285441** [anka-213/webcomic_reader#12]
Webcomic reader has a working configuration for mangapark. mangapark.com currently redirects to mangapark.me as the working domain, so small update is needed to restore functionality. 2 lines added/updated for a quick fix.

Addition to the metadata block:
`// @include        http*://mangapark.me/*`

And change on line 3170 from:
`	{ url:	'mangatank.com|mangapark.com|mangawindow.com',`
to
`{	url:	'mangatank.com|mangapark.com|mangawindow.com|mangapark.me',`

**Comment by anka-213** [comment]
Thanks for the patch. If you create a pull request, I can include it
straight away. You can edit and submit the change directly from Github.
