### ISSUE TITLE
Fails to load.

### ISSUE THREAD

**Issue by S0X-LT** [anka-213/webcomic_reader#120]
Using Waterfox 56.2.1 with ViolentMonkey v2.9.5.

Webcomic reader fails to load. Here's what web console throws:

![2018-07-01_07-23-22](https://user-images.githubusercontent.com/13443016/42134030-b6784bfe-7d01-11e8-9cb0-c96af7e09646.jpg)

Tried an older version and found out that it works.
After trying various older versions I found out that the last one that works is from April 28, So one of the commits from April 30 must have broken it.

**Comment by Morphello** [comment]
Vivaldi Browser 1.15  - Tampermonkey 4.6

Experience the same issue (extension not loading). Reverted back to a 2017 version and it continued to work. Have not determined which commit broke the addon and don't have a console output.

**Comment by anka-213** [comment]
Yes, those were some syntax errors on my part. Thanks! Surprised that it worked at all in any browser.
 It should work with the latest version now.
