### ISSUE TITLE
Im dumb and I'm having trouble setting up marktrail.com

### ISSUE THREAD

**Issue by Ampelioides** [anka-213/webcomic_reader#123]
Hi, I really love this script, and its previous iterations. However, i'm dumb as bricks and have approx 0 coding knowledge.

http://marktrail.com/ seems to be structured like a lot of other comic sites, but adding it to the @include list just makes it mess with the calendar for some reason. Any help you could spare would be greatly appreciated. gotta get my edutainment going! got 22 years of mark trail to catch up on!

**Comment by anka-213** [comment]
Here you go! The default filter found the wrong image on that site, but now it should work.
