### ISSUE TITLE
http://dynasty-scans.com/

### ISSUE THREAD

**Issue by ybnrmalatall** [anka-213/webcomic_reader#15]
Is there any possible way to get this working?

**Comment by anka-213** [comment]
@ybnrmalatall  Please check if this new version works.

**Comment by ybnrmalatall** [comment]
@anka-213 You're a god. That site needs this the most. Thank you so much, it works.

**Comment by Tmp341** [comment]
It seems it's working now. Thanks @anka-213

**Comment by anka-213** [comment]
Great! =)
