### ISSUE TITLE
Tries to load resource from userscripts.org

### ISSUE THREAD

**Issue by joelbu** [anka-213/webcomic_reader#18]
Hey anka
Tampermonkey recently started warning me, that Webcomic reader was trying to access the following URL: http://userscripts.org/scripts/source/59842.meta.js?1460204422209 of course that domain has been down for quite some time now, so this must be some sort of artefact in the script? It seems to me that it has to do with the auto updater.
Probably this needs to be removed or adapted to the new script locations.
Brest regards

**Comment by anka-213** [comment]
Yeah, I noticed this too. I can probably just remove it, since tampermonkey
and (I assume?) greasemonkey have built in autoupdaters.

**Comment by Tmp341** [comment]
@anka-213 [Look Here](http://www.greasespot.net/2012/02/automatic-script-updates-come-to.html)
