### ISSUE TITLE
Add demonicscans.com

### ISSUE THREAD

**Issue by williammc30** [anka-213/webcomic_reader#26]
This group seems doing good scans, i tried adding it but proved too difficult, if it isn't too much of a bother can you add it please.
http://www.demonicscans.com/

**Comment by anka-213** [comment]
Actually, if you just add the sit to the include list (you can do that without editing the script itself), it will at least partially work automatically. The main thing that doesn't work out of the box for the site is the back-button.

**Comment by williammc30** [comment]
thank you for your quick reply. the issue is that there is a URL with keyword "NEXT" in it so when i click next it automatically redirect me to that URL and not to the next page.

**Comment by anka-213** [comment]
Can you link me to a page with that issue?

**Comment by williammc30** [comment]
the page seems down from my end, here is a page with same reader and the same issue
[http://raws.yomanga.co/read/wizardly_tower/ko/0/11/page/10](url)

**Comment by anka-213** [comment]
That is not how you format links in markdown by the way.
Just paste the link as it is or use `[Title of page](http://www.example.com)` to get "[Title of page](http://www.example.com)".

**Comment by williammc30** [comment]
sorry about that and thanks for all your help

**Comment by anka-213** [comment]
It should work now. You can force an update in greasemonkey/tampermonkey to see the change right away. Don't forget to disable any custom config for the sites, so you use the updated version.
