### ISSUE TITLE
Bato.to not working properly

### ISSUE THREAD

**Issue by HASJ** [anka-213/webcomic_reader#30]
First, thanks for taking on this wonderful script!

I just tried bato.to and it doesn't seem to work well. It just doesn't.
Going forward or backwards gives a blank page, saying "No content select" with a URL unrelated to the chapter you're reading, so I guess the next/previous detector is broken.
Minimalistic layout doesn't work well either.

**Comment by Tmp341** [comment]
It is working for me. But i got "no content selected" error like this: First, i opened a manga without logging in. Then from the menu, i've tried to open an older chapter, got "there was an error, you don't have permission or you haven't logged in"  like error. when i pressed "back" button, got that "no content" error with the [http://bato.to/reader](http://bato.to/reader) link.
Other than that, everything including "minimalistic layout" is working.
[Screen Capture](https://cloud.githubusercontent.com/assets/1683388/16757836/f377e838-4816-11e6-98fb-9b656dca8de8.jpg)

**Comment by HASJ** [comment]
Weird...
I deleted and installed anka's WCR and it worked. Guess it was broken in ameboide's version and the soft update didn't work well.
Thanks.
