### ISSUE TITLE
Site request for thehiveworks.com

### ISSUE THREAD

**Issue by DCTest1** [anka-213/webcomic_reader#32]
It's a Network of Webcomics and I think they all use the same program.
This would mean you only need ONE script to make the 30+ different 
webcomic sites work.
I need it for these sites:
http://www.marycagle.com/
http://www.kiwiblitz.com/ (already Logged but doesn't work)
http://www.sleeplessdomain.com/
They're all part of http://www.thehiveworks.com/

**Comment by anka-213** [comment]
I've added a generic fix that should prevent thehiveworks sites from being broken, but we'll still have to add the individual sites to the list.

The css is a bit mangled up on marycagle.com, and the commentaries on the bottom is not added yet. (The site uses images for layout, so it's difficult to add buttons without messing upp the layout)

**Comment by DCTest1** [comment]
Thanks
