### ISSUE TITLE
goblinscomic.org broken

### ISSUE THREAD

**Issue by flying-sheep** [anka-213/webcomic_reader#35]
i get this in the console:

```
cambia[1]: TypeError: get(...) is null"
```

**Comment by flying-sheep** [comment]
wow, that was fast!

sadly it didn’t fix my problem. i still see the same error. any way i can help you debug? some events to hook into to see what’s going on?

PS: the last page seems to be broken ATM (i.e. its back link doesn’t point to something valid), so to debug it, you need to start on some other page (e.g. [the first](http://www.goblinscomic.org/06252005/))

**Comment by anka-213** [comment]
Hmm... strange! It works for me now. Do you have any custom settings for the site?

**Comment by anka-213** [comment]
Also, are you using FF or chrome? I have only tested the change in chrome/tampermonkey.

**Comment by anka-213** [comment]
Aha, there was a small difference in behaviour between Tampermonkey and Greasemonkey. I'm kind of surprised that my original code worked at all.

**Comment by flying-sheep** [comment]
firefox, but you seem to have figured it out yourself :wink:

**Comment by anka-213** [comment]
It should work now.

**Comment by flying-sheep** [comment]
like a charm, thank you!
