### ISSUE TITLE
Script no longer works without greasemonkey/tampermonkey

### ISSUE THREAD

**Issue by anka-213** [anka-213/webcomic_reader#37]
Mostly because I'm using unsafeWindow.

**Comment by DCTest1** [comment]
did you just open a bug report on your own script?
if you don't know how to fix it, how are the rest of us supposed to know? ;-)

**Comment by anka-213** [comment]
I opened it as a reminder for myself. ;)

**Comment by anka-213** [comment]
Ok, that fixed that part, but I still don't get it to run on iOS. Well, I don't have a debugging setup for iOS safari, so it'll have to be for now.
