### ISSUE TITLE
Need some sites added.

### ISSUE THREAD

**Issue by ybnrmalatall** [anka-213/webcomic_reader#45]
(**Works with just adding the url**)
`http://leylinescomic.com/comics/*`
(**Does not work with just adding url**)
`http://project-apollo.net/mos/*`
`http://afterstrife.com/?p*`

**Comment by Yoposoc** [comment]
Please add this as well! It doesn't work with just the url added.
http://incase.buttsmithy.com/comic/

**Comment by anka-213** [comment]
- [x] http://leylinescomic.com/comics/*
- [ ] http://project-apollo.net/mos/*
- [ ] http://afterstrife.com/?p*
- [x] http://incase.buttsmithy.com/comic/

**Comment by anka-213** [comment]
@ybnrmalatall It seemed to me like afterstrife worked with just adding the url. Is there any problem I missed?
