### ISSUE TITLE
kissmanga's "Are you human" CAPTCHA

### ISSUE THREAD

**Issue by Yoposoc** [anka-213/webcomic_reader#46]
For a while now, kissmanga's "Are you human" security things have caused this extension to break. When you encounter this, you are redirected to the start of the chapter, then get it again on the same page, making it impossible to read further with the extension on. Can you fix it?

**Comment by anka-213** [comment]
It turned out that the extension was downloading the page once per image, instead of once per chapter, which the site didn't like. It should work now. Please reopen if it's still an issue.

**Comment by Yoposoc** [comment]
It seems like it's not working anymore. Not sure why this time. At a certain page, the page that I'm reading will revert to the beginning, creating an endless loop. I have to turn the extension off the read it properly.

**Comment by anka-213** [comment]
You can also disable the extension for a specific comic by clicking
"disable wcr for this site" on the greasemonkey/tampermonkey menu.

I'll look into this when I have time, but I've been a bit busy lately.

>
