### ISSUE TITLE
The comic at marryme.keenspot.com not working.

### ISSUE THREAD

**Issue by ybnrmalatall** [anka-213/webcomic_reader#54]
I assume it's not working for the rest of the keenspot comics either.
[http://marryme.keenspot.com/d/20120823.html](http://marryme.keenspot.com/d/20120823.html)

**Comment by anka-213** [comment]
Oops, it only took me 11 months to make this simple fix. Well, now it should work again now. Too bad the final update was 4 months ago. :P
