### ISSUE TITLE
Bato.to

### ISSUE THREAD

**Issue by ybnrmalatall** [anka-213/webcomic_reader#6]
I see you did get it working. Although it won't load any images... It does re-size and wrap around the irritable reader they use. It could be that it's Chrome.

![v5yn8hs](https://cloud.githubusercontent.com/assets/7112828/12981010/eb185d76-d0ac-11e5-8363-23ee17309938.png)

**Comment by anka-213** [comment]
Strange. I am using chrome (with Tampermonkey) too, so that shouldn't be the problem. Can you post the output from the console (press F12 to open it)?

**Comment by anka-213** [comment]
I tried it again with a fresh install in a new profile, and it still works for me. Please try that as well, to see if there is some problem with custom settings or a conflict with another plugin.

**Comment by ybnrmalatall** [comment]
I erased tampermonkey beta and added the script to stable. It still doesn't work. I even need to add "// @include        */bato.to/reader*" for it to enable on the page.

**Comment by ybnrmalatall** [comment]
ahhhhhh... It works fine on `http` but I load the page in `https`... is there any way to get the pages to load properly in https?

**Comment by anka-213** [comment]
Aha, I didn't notice that the https in your screenshot. It is a "Mixed Content" issue. The Batoto links to the http version of the page, which the script then tries to load in the background. But that is forbidden from a https page.

**Comment by anka-213** [comment]
(Feel free to reopen this if there are still issues)
