### ISSUE TITLE
Recent changes to e-hentai.org

### ISSUE THREAD

**Issue by FurtiveCutless** [anka-213/webcomic_reader#62]
Recently the website e-hentai.org has changed their URLs for galleries and as a result this scipt no longer works.

The switched from the old `http://g.e-hentai.org/*` to `https://e-hentai.org/*`

I just wanted to inform you so you can possibly adjust the scipt, whenever you have the time to do so.

**Comment by Yoposoc** [comment]
`https://exhentai.org` does not seem to work either.

**Comment by lauyuen** [comment]
I've fixed it in the pull request that @anka-213 still hasn't accepted.

**Comment by anka-213** [comment]
@lauyuen Oops, sorry. It's merged now.
