### ISSUE TITLE
Please add mangaseeonline.us

### ISSUE THREAD

**Issue by kobuki** [anka-213/webcomic_reader#66]
Could you please add: http://mangaseeonline.us/ - it used to be mangasee.com but have been fully redesigned. It also has a bar at the top that used to cover the images when zoomed in fullscreen. Could you look into that, too?

**Comment by Vorror** [comment]
Also interested

**Comment by Vorror** [comment]
New to the library, but I fixed it :)

**Comment by kobuki** [comment]
Looks to be working great!

**Comment by kobuki** [comment]
@Vorror it's working great, with a small issue. The top navbar is indeed hidden but in the old mangasee.com version it was just made scrolled out of view. Now you disabled it completely so important functions like bookmarking is unavailable with the script enabled. Is it possible to make it scroll out somehow like the old one?

**Comment by Vorror** [comment]
@kobuki Sure, let me look into it

**Comment by Vorror** [comment]
@kobuki I added the bookmark button below the image. Does that work for you?

**Comment by kobuki** [comment]
Well, it would be nice to have the full bar somewhere out of view, since it has other functions, like All Pages for manhwa reading and a home page link. A compromise might be to let the bar appear and images stretch in the available space but it kinda ruins the view and we'd have less space.

**Comment by Vorror** [comment]
Just pushed a new build. The full navbar is at the bottom. Although now that you mention the all pages view, I'll probably need to look into that today or tomorrow.

**Comment by Vorror** [comment]
Ok, I think I got it. The original page layout will be the same with a non-floatly navbar. But in mini-layout it's not displayed anyway. And page changes will just jump to the image anyway.

**Comment by kobuki** [comment]
Hmm, functions are there but looks weird :) I haven't really dug into the reader code but all sites work using the simple method of positioning the images to fill the screen and all surrounding content remains but hidden, out of view. A simple mouse scroll reveals the original content surrounding the images. I think this is the way to do it though in the case of this site it might be difficult or impossible, I can't tell.

**Comment by kobuki** [comment]
We posted at the same time - what you last wrote might be it.

**Comment by Vorror** [comment]
@kobuki :) Yea I'm new to the source of webcomic, read just enough to implement the site. I do need to look into the all pages button.

**Comment by anka-213** [comment]
@Vorror Wow! Thanks for your contribution. Let me know if you have any WCR related questions.

**Comment by Vorror** [comment]
@anka-213 Thanks! It seems for single page mode they embed dozens of images into a single div. Is there any way for WCR to handle that? If not I believe that was the only issue remaining.

**Comment by anka-213** [comment]
@Vorror Not really. But as a workaround, I've put the additional images in an "extras" block on some sites. See for example mspaintadventures and webtoons.

**Comment by anka-213** [comment]
If there is still trouble with multiple images on a page or something, open a new issue with a link to an example of that.

**Comment by kobuki** [comment]
Good work! All Pages seems to work as well.

I see an issue though, which belongs here. Let me know if I have to open a new issue. The first image of any single chapter is shown in the original layout, not stretched to the window. A page-next click snaps it to place and subsequent pages are displayed according to the WCR settings.
