### ISSUE TITLE
mangastream is now using readms.net

### ISSUE THREAD

**Issue by sercankd** [anka-213/webcomic_reader#69]
therefore script does not work anymore

**Comment by iZN1337** [comment]
You mean MangaStream*

**Comment by Lunarhawk** [comment]
Adding readms to the script does make it work somewhat but there are indeed issues (for example the new issue for some reason has every page in it try to load the first page from 2 chapters prior and then the script breaks)

**Comment by lauyuen** [comment]
I've fixed it in a pull request that @anka-213 has yet to merge. You can check out the raw at https://github.com/lauyuen/webcomic_reader/raw/fd50d5caf4393c00089703ff2cdcb56510626e5e/webcomic_reader.user.js

**Comment by sercankd** [comment]
yeah mangastream* sorry about typo

**Comment by anka-213** [comment]
@Lunarhawk Please submit a new issue for those problems, I'm closing this now.
