### ISSUE TITLE
Madokami no longer working

### ISSUE THREAD

**Issue by byjtje** [anka-213/webcomic_reader#70]
https://manga.madokami.al/ currently is not working, even though there is a inclusion for it by default in it. When pressing the Greasemonkey icon, it says that the script is running, however nothing of it seems to be loading (no buttons, preloading and so on). I tried reading into the userscript code, but don't understand anything, sorry! Hope somebody here could help me with it, many thanks in advance!!

**Comment by MDosky** [comment]
My bad, I didn't test it on Firefox with Greasemonkey.
I opened a pull request with the fix.

**Comment by byjtje** [comment]
It is working now, thank you very very much!!
