### ISSUE TITLE
EatManga URL change

### ISSUE THREAD

**Issue by davidthemaster30** [anka-213/webcomic_reader#72]
Hi, 

The url for EatManga had changed from eatmanga.com to eatmanga.me.

Adding an include for eatmanga.me with the same scripting as eatmanga.com fixes it.

I suck at Git though and can't find how to do pull (push?) requests.

Thanks.

**Comment by anka-213** [comment]
It's actually very easy to do it in Github. :)
 Just open the file in my repo, press the edit button (pencil icon) and edit away. When you are done, write a short summary of the changes (preferably mentioning this issue number, eg. "Update EatManga URL. Fixes #72") and press the "Propose file change" button at the bottom and then the green "Submit pull request" button. 

Here is Github's guide: https://help.github.com/articles/editing-files-in-another-user-s-repository/
