### ISSUE TITLE
Remembered pages

### ISSUE THREAD

**Issue by byjtje** [anka-213/webcomic_reader#77]
Is there any way to hide/ add a confirmation to the delete remembered page button? Currently there is no confirmation and no way to recover accidentally lost pages. I tried hiding them with uBlock, however I only manage to block one button at a time >.<
Many thanks in advance!!

**Comment by anka-213** [comment]
If you want to use uBlock, the filter `###wcr_listabm > div > button` should work.

**Comment by byjtje** [comment]
Yay that fixes it, thanks a lot!!
