### ISSUE TITLE
senmanga

### ISSUE THREAD

**Issue by Yoposoc** [anka-213/webcomic_reader#8]
Thanks a lot for taking this on. 

senmanga is still not working, both regular and raw.

**Comment by Yoposoc** [comment]
again, not working.

**Comment by anka-213** [comment]
@Yoposoc It seems to work for me. What is broken?

**Comment by Yoposoc** [comment]
Sorry, it's specifically the raw.senmanga.com version.

**Comment by Tmp341** [comment]
@Yoposoc I've tried raw.senmanga and it's working for me.

**Comment by Yoposoc** [comment]
For some reason, it's not working for me. http://puu.sh/oeDKQ/133f55e49e.jpg
It simply seems like the extension doesn't recognize the page, although greasemonkey tells me the extension is on when I'm on raws.senmanga.com/*

**Comment by anka-213** [comment]
@Yoposoc Do you get any error messages in the console? You can open the console with F12.

**Comment by anka-213** [comment]
@Yoposoc Actually, I think I found the issue. The https-version was not added to the list. http://raw.senmanga.com works, but https://raw.senmanga.com doesn't.

**Comment by Yoposoc** [comment]
I wasn't accessing through https, but I tried adding that to my included list. Still doesn't work. Nothing shows up in the console either. I thought maybe I disabled it for raws in the past, so I looked at my excluded pages list, but it's not there either. I'm stumped.

**Comment by Tmp341** [comment]
@anka-213 Yeah, i've added https and stopped working. Other than that it's working [Screen Shot](http://puu.sh/ofnP1/ff016d9a09.jpg)

**Comment by anka-213** [comment]
@Yoposoc Very strange. It sounds like the script is not executed at all for some reason, otherwise there would be text in the console.

Are you using FF or Chrome? In TamperMonkey there is a small number on the logo, which indicates if a script is running. In GreaseMonkey, the drop-down menu (by the logo) should have Webcomic Reader in the bottom.

**Comment by Yoposoc** [comment]
@anka-213 I am using FF, and can confirm that webcomic reader is included in the drop-down menu, which is why it's so strange. I've turned off adblocks too... http://puu.sh/ogi1l/c2bfb2825d.jpg

**Comment by anka-213** [comment]
@Yoposoc There really should be output in the console in that case. Can you try reloading the page with the console open? (Ctrl-Shift-J was apparently the way to open the console in FF)

You might also want to try resetting firefox or creating a new profile, with just greasemonkey and nothing else. It might be something else that interferes with the script. (I still can't replicate the behavior)

**Comment by Tmp341** [comment]
@Yoposoc Try disabling other scripts other than reader. And check again.

**Comment by Yoposoc** [comment]
I've tried it with all other extensions disabled. No go. I disabled all add-ons too except greasemonkey, and got this. http://puu.sh/ojTJl/57f1ec6b0a.png I can confirm the extension is working on other sites
The page I was looking at was here: http://raw.senmanga.com/Senpai-Sore-Hitokuchi-Kudasai/26/1
I'm not sure of a way to create a new profile without huge hassles with my current one, so I'd rather not do that...

**Comment by Tmp341** [comment]
Did you disabled other scripts too?

**Comment by Yoposoc** [comment]
Yup.

**Comment by anka-213** [comment]
@Yoposoc It's actually very easy to create a new profile. Just launch ff
with the flag "-P" (firefox -P) and the profile manager shows up. Profiles
do not interfer with each other, so it's safe to experiment in the new one.

**Comment by Yoposoc** [comment]
@anka-213 I'm trying to be cautious. Does it save tab states too? If I close it and then relaunch ff without the flag, I'll be back where I left off?

**Comment by Tmp341** [comment]
If you can't, you can go %appdata%\Mozilla\Firefox\ and change manually "profiles.ini" file.

**Comment by Yoposoc** [comment]
Ok, so I used the -p flag to make a test profile, installed just greasemonkey, the extension, and adblock, and directly went to raw.senmanga.com and tested it out. It works. So it must be something in my current profile.... But no idea what. Would the only solution be to remake a new profile?

**Comment by anka-213** [comment]
It's hard to say. You can try firefox's "refresh profile" feature, which
basically makes a new profile and imports all bookmarks and some settings
from the old one. The old profile is backed up, so you won't loose any data.

Another alternative is to run two profiles in parallel, which is possible
with a flag. (Without the flag, the new session will just connect to the
old one)

>

**Comment by Tmp341** [comment]
You said you tried senmanga without anything other than greasemonkey & webcomicreader, but no luck. Starting new profile solved the issue. This might indicate two things. 

- First, your settings cause the problem. Like cookies etc. Check those.
- You have changed one or more settings in "about:config" . Check those.

Nothing else comes to my mind.

**Comment by Yoposoc** [comment]
Clearing cookies didn't help. Not sure what to do in about:config, so haven't touched it. Well, since switching profiles was harmless and relatively quick I think I'll just use that.... Thanks a lot for helping guys.
