### ISSUE TITLE
Script stopped working for Mangahere

### ISSUE THREAD

**Issue by Nanomachine-san** [anka-213/webcomic_reader#87]
Haven't been using Mangahere at all so I'm not entirely sure when this started happening, but when I tried visiting Mangahere, the script wouldn't run at all.

**Comment by javiervera86** [comment]
It also stopped working in mangafox.me. Please fix it.

**Comment by kobuki** [comment]
For me, both sites work with the script (latest release version).

**Comment by anka-213** [comment]
@javiervera86 Please open a separate issue for that.
