### ISSUE TITLE
Please try to add mngdoom.com

### ISSUE THREAD

**Issue by Qiler** [anka-213/webcomic_reader#96]
I tried adding support for it myself trough editor but was unable to add prev/next page support. It seems that this website uses jQuery script on buttons to do the pageturning. Unfortunately it is beyond my abilities.

**Comment by anka-213** [comment]
I've added the site now. Please tell me if there are any issues.

**Comment by Qiler** [comment]
Wow. That was fast. Seems to work like a charm. Thank you.
